name: jurnal_prakerin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  another_flutter_splash_screen: ^1.2.1
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.3
  flutter_html: ^3.0.0-beta.2
  flutter_map: ^7.0.2
  flutter_otp_text_field: ^1.2.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdfviewer: ^26.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/profile.png
    - assets/images/not_found.png
    - assets/help.pdf
